# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85afa5962cf177e345fdd8062897821375afd740348e55e185bec8af6a9b00f385d8e679a7ab84cda9ed3e66f8d537e35bf7d00e34fdd693a2a07165376f6540

test:
  secret_key_base: 0a966d3c697e8dcf966af492adb0be6542c53aa9a5fea2a4b89a660b8cc934ccb332f7a9f3a64798a914773c5e7269e340ee47221e022b8408e148304ff21958

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
